version: '3.8'

services:
    #nginx+php
    app:
        build:
            context: ./app/docker
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - ${APP_PORT}:80
            - ${APP_HTTPS_PORT}:443
        volumes:
            - ./app:/var/www/app:cached
            - ./.git:/var/www/app/.git:cached
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
            TIMEZONE: ${TIMEZONE}
        restart: ${RESTART_CONDITION}
        links:
            - db

    #mysql
    db:
        image: library/mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABSE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: ${TIMEZONE}
        volumes:
            - db:/var/lib/mysql
        restart: ${RESTART_CONDITION}

    #phpmyadmin
    phpmyadmin:
        image: bitnami/phpmyadmin:5.0.1
        ports:
            - 127.0.0.1:${PMA_HTTP_PORT}:80
        environment:
            DATABASE_HOST: db
        restart: ${RESTART_CONDITION}
        depends_on:
            - db
        links:
            - db

volumes:
    db: